theme: minima

title: The first thing
author: fiberproduct
email: usjtuhzjor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Nothing for description here.

# social links
# twitter_username: N/A # DO NOT include the @ character, or else the build will fail!
github_username:  fiberproduct # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
